name: Hugging Face Keep Alive

on:
  schedule:
    # Berjalan otomatis setiap 20 menit tanpa perlu kamu push kode
    - cron: '*/20 * * * *'
  workflow_dispatch: # Supaya bisa kamu klik tombol "Run" manual dari web GitHub

jobs:
  ping-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Hugging Face Endpoint
        run: |
          curl -s https://zyuuxyncool-otakudesu-real-api.hf.space/health
